### ISSUE TITLE
句読点の統一

### ISSUE THREAD

**Issue by LiltoneJG** [JotaroS/FluidDynamics2#1]
【要検討】になってたのでスレ立てました。現在は半角コンマ・ピリオドに統一されています。

**Comment by Liltone195** [comment]
【要検討】になってたのでスレ立てました

**Comment by JotaroS** [comment]
google IMEさんの設定でデフォルト句読点を変える機能を適用してそのまま打ち込んでいたのですが、なにか問題ありそうですかね

**Comment by ossan-arrow** [comment]
多分Google IMEの設定だと全角のが出てくるんだと思います（「，」「．」）
今の所は数式との整合性を考えて、半角に統一しています（「,」「.」）が、もう少し考えてみます……。

**Comment by ossan-arrow** [comment]
これまでの流儀通り、半角のカンマ・ピリオドで統一する事にしました。日本語入力時には少し面倒だとは思いますが、半角カンマ・ピリオドの後に半角スペースを挿入するようお願いします。
