### ISSUE TITLE
添え字付きの文字のオーバーラインはどこまで引くか

### ISSUE THREAD

**Issue by ossan-arrow** [JotaroS/FluidDynamics2#2]
\overline{u}_mとすべきか、\overline{u_m}とすべきか？

**Comment by LiltoneJG** [comment]
意味的には

``` math
\oveline{u_m}
```

が良さそう？

**Comment by ossan-arrow** [comment]
私もそう思うのですが、そう書いてある教科書を見た記憶が無くて……もしそんな記述を見つけたら教えてください(´Д` )

**Comment by LiltoneJG** [comment]
とりあえず[講義ページ](http://www.mesl.t.u-tokyo.ac.jp/nagare/)の資料には無かった

**Comment by JotaroS** [comment]
ぱっと画像検索で探してみると\oberline{u}_m的記述しか見当たりませんね

**Comment by ossan-arrow** [comment]
ではひとまず伝統に従って、そちらの方針を採用する事にしましょう。もし執筆中に例外的な事例が出てきたら教えてください。
