### ISSUE TITLE
subsubsectionの数字フォント

### ISSUE THREAD

**Issue by JotaroS** [JotaroS/FluidDynamics2#4]
"1.1.1 流れ学第1との違い"の"1.1.1"のフォントが統一がとれていない問題

**Comment by ossan-arrow** [comment]
「1.1.1」と「第1」が違うということでしょうか？（「1.1.1」の中では同じに見えます）

**Comment by JotaroS** [comment]
いや、"Chapter 1" と "1.1"がサンセリフなのに対して"1.1.1"がセリフ体だから気になるという意味ですm(_ _)m

**Comment by ossan-arrow** [comment]
ああなるほど。この場合、「1.1.1」はいっその事無くしてしまった方が良いような気がします。

**Comment by JotaroS** [comment]
それ実際ありだね

**Comment by ossan-arrow** [comment]
その場合、\subsubsectionに下線を引くなり、真ん中に持ってくるなりすると視認性が良くなるかもしれません……その辺りは好みの問題も有るのでお任せします。

**Comment by JotaroS** [comment]
真ん中ってページの真ん中ってことでしょうか？

**Comment by ossan-arrow** [comment]
左右方向の中心って事ですね

**Comment by JotaroS** [comment]
なるほど．読みやすさの観点から，そのまま左端に置くのがよさそうです
