### ISSUE TITLE
行列を囲む括弧の種類

### ISSUE THREAD

**Issue by ossan-arrow** [JotaroS/FluidDynamics2#5]
パーレンにするか、ブラケットにするか？

高校の教科書をはじめとして、一般的な理論の教科書ではパーレンで囲まれているものが多いようです。しかし、数値解析学など、コンピュータに大きな行列を処理させるような分野では、パーレンでは組版しにくいのでブラケットで囲まれているものが多いようです。

流体力学は数値解析学とも密接に関連しており（数値流体力学）、大規模な行列を扱うことが多いこと、そして後々の学習のためにもブラケットを採用するのが望ましいと考えますが、いかがでしょうか。異議無ければそれで行きます。

**Comment by LiltoneJG** [comment]
賛成で！

**Comment by JotaroS** [comment]
CFDの論文にせよFEMの教科書にせよ，行列はほとんどがブラケットで囲まれているものが多いようです．とりあえずブラケット[]で行きましょう
